# Copyright 2018 Patrick Bareiss

# This file is part of Ypsilon.

# Ypsilon is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# Ypsilon is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with Ypsilon.  If not, see <http://www.gnu.org/licenses/>.

---
# This playbook revert the configured snapshot

- name: revert to snapshot {{ snapshot }}
  shell: VBoxManage snapshot {{ vm_name }} restore {{ snapshot }}
  register: revert_snapshot_output  
  when: SIEM_target == 'splunk' 

- name: Debug revert snapshot output
  debug:
    msg: "{{ revert_snapshot_output.stdout }}"
  when:
    - log_level == 'debug'
    - SIEM_target == 'splunk'

- name: start VM from snapshot
  shell: VBoxManage startvm {{ vm_name }} --type headless
  register: start_VM_output
  when: SIEM_target == 'splunk' 

- name: Debug start VM snapshot output
  debug:
    msg: "{{ start_VM_output.stdout }}"
  when:
    - log_level == 'debug'
    - SIEM_target == 'splunk'

...
